name:         hyam2
version:      "0.0.0.0"
author:       Chan Beom Park
maintainer:   cbpark@gmail.com
license-file: LICENSE
github:       cbpark/hyam2
category:     Physics

ghc-options:  -Wall -Wcompat -O2 -funbox-strict-fields

dependencies:
  - base >= 4.12.0.0 && < 5
  - bytestring
  - hmatrix
  - pipes
  - pipes-bytestring
  - zlib
  - hep-utilities

executables:
  hyam2:
    main: hyam2.hs
    source-dirs: src
